# 数値計算  
- **Submission date**: 2017/10/06  
- **Team**: へび  
- **Members**:  
    - #5531 Akihiro Nitta  
    - #???? Y K
    - #???? K S

## モジュールの読み込み 
- [numpy](http://www.numpy.org) is the main package for scientific computing with Python.  
// - [scipy](http://www.scipy.org)  
// - pprint  

In [77]:
import numpy as np
# import scipy.linalg as linalg
# import pprint

## 2.2.4 課題  p. 14
1. printfを使って次のように表示せよ.  
   i) Hello world.  ii) 1+1=2  
1. 次の数を順に表示せよ．  
    i)1から5までの整数．  
    ii) 5から1までの整数.  
    iii) 1から10にある偶数．  
1. 9x9表を作れ．  
1. 1 から 5 までの和を求めよ.  
1. nを5にして，n!=n×(n−1)×(n−2)⋯3×2×1n!=n×(n−1)×(n−1)⋯3×2×1を求めよ.  

In [ ]:
# 1.
# i)
print('Hello world')
# ii)
print('1+1=2')

In [ ]:
# 2.
# i)
print('i)')
for i in range(1, 6):
    print(i)
# ii)
print('ii)')
for i in reversed(range(1, 5)):
    print(str(i))
# iii)
print('iii)')
for i in range(1, 11):
    if i % 2 == 0:
        print(i)

In [ ]:
# 3.
for i in range(1, 10):
    for j in range(1, 10):
        print(str(i*j), end=' ')
    print('')

In [ ]:
# 4.
sum = 0
for i in range(1, 6):
    sum = sum + i
print('sum = ' + str(sum))

In [ ]:
# 5.
n = 5
factorial = 1
for i in range(1, n+1):
    factorial = factorial * i
print(factorial)

## 2.3.8 課題  p. 20  
1. 1から100までの整数のうち5個をランダムに含んだ配列を生成せよ．  
1. さいころを１００回振って，出た目１から６が何回出たかを表示せよ．  
1. コイン６枚を一度に投げて，表向きの枚数を数えるプログラムを書け．  
1. 0から9までの整数5個から5桁の整数を作れ．（１桁目が０になっても気にするな）  
1. 小数点以下8桁のそれぞれの桁の数を配列に格納せよ．8桁の少数は以下のようにして作られる．  
1. 255以下の10進数をランダムに生成して，8桁の2進数へ変換せよ．整数の割り算には irem(余り) と iquo(商) がある. 使用法は以下の通り．  

In [59]:
# 1.
array_1 = np.random.randint(1, 101, 5)
array_2 = np.array([])

for i in range(10):
    array_2 = np.append(array_2, np.random.choice(array_1))

print(array_1, array_2)

[27 72  4 22 72] [ 72.   4.   4.  72.  72.  27.  22.  22.  22.   4.]


In [63]:
# 2.
count = np.zeros(6)

for i in range(100):
    count[np.random.randint(0, 6)] += 1
    
print(count)

[ 12.  17.  19.  24.  15.  13.]


In [29]:
# 3.
coin = np.random.rand(6)
coin = coin>0.5
print(coin.sum())

3


In [41]:
# 4.
values = np.random.randint(0, 10, 5)
value = 0

for v in values:
    value *= 10
    value += v

print(values, value)


[4 4 2 7 9] 44279


In [76]:
# 5.
value = np.random.rand()
array = np.array([])

print(value)
for i in range(8):
    value = value - int(value)
    value = value*10
    array = np.append(array, int(value))

print(array)



0.01155349252321003
[ 0.  1.  1.  5.  5.  3.  4.  9.]


In [ ]:
# 6.

value = int(np.random.rand() * 255)
value = 122
print('value: ' + str(value))
bin_value = ''
while(value > 0):
    if value % 2 == 0:
        value /= 2
        bin_value += '1'
    else:
        value -= 1
        value /= 2
        bin_value += '0'
print('bin_value: ' + str(bin_value))


## 2.4.4 課題  p. 24  
1. 西暦を代入したら，明治，大正，昭和，平成で答えてくれるプログラムを作成せよ．西暦1868,1912,1926,1989年をそれぞれの元年とする．  
1. 整数を代入したら，それ以下の素数をすべて表示するプログラムを作れ．素数かどうかの判定はMapleコマンドのisprimeを用いよ．  
1. pが素数でp+2も素数のとき，これらは双子の素数と呼ばれる．10以上，100以下の双子の素数を全部見つけて出力せよ．  
1. 素数判定を原理から実現せよ．ある数nが素数かどうか(自分自身の数nと1以外の数で割りきれないかどうか)を判定せよ．割り算の余り(剰余)はiremで求まる．  
    例えばとして変数residue(余りの英語)をprintfしてみよ．番兵を置いておいて，n­1から2までの数でnを次々と割っていき，一度でも割り切れれば番兵にマークをつける．ループが終わった後に番兵のマークを見て素数(prime number)かどうかを判定すればよい．
1. うるう年かどうかを表示するプログラムをかけ．\\うるう年は4で割り切れる数の年．ただし，100で割り切れる年はうるう年でなく，400で割り切れる年はうるう年．
1. ゴールドバッハの予想 \\「6以上の偶数は二つの素数の和として表わされる」という予想を100以下の偶数について検証せよ．あらかじめ100までの素数をリストアップしておいてそのなかから組み合わせを探すと便利

In [ ]:
# 1.
year = int(input('year >>> '))
year_jp = 0

# 平成
if year >= 1989:
    year_jp = year - 1989 + 1
    print('平成' + str(year_jp) + '年')
# 昭和
elif year >= 1926:
    year_jp = year - 1926 + 1
    print('昭和' + str(year_jp) + '年')
# 大正
elif year >= 1912:
    year_jp = year - 1912 + 1
    print('大正' + str(year_jp) + '年')
# 明治
elif year >= 1868:
    year_jp = year - 1868 + 1
    print('明治' + str(year_jp) + '年')
# それ以外
else:
    print('unknown')

In [ ]:
# 2.
def isprime(num):
    '''
    Arguments:
    num -- 素数判定対象のint値
    
    Returns:
    True/False -- 素数であるか否か
    '''
    buff = num
    bool_prime = True
    for i in range(2, num):
        if buff % i == 0:
            bool_prime = False
            break
    return bool_prime

value = int(input('value > '))
print(isprime(value))

for i in range(2, value+1):
    if isprime(i):
        print(i)

In [ ]:
# 3.
for i in range(10, 100+1):
    if isprime(i) and isprime(i+2):
        print(str(i) + ', ' + str(i+2))

In [ ]:
# 4.


In [ ]:
# 5.


In [ ]:
# 6.


## 2.4.5 課題  p. 29
1. **三角形の面積**  
    底辺と高さを引数として，面積を返す関数areaを作れ．  

1. **MyIsprime**  
    前章の課題４で求めた素数判定プログラムをprocにせよ．  

1. **ルートの距離二つの位置座標**  
    x1:=[0.0, 0.0] x2:=[1.0, 1.0]から距離を求めるMyDistance関数を作れ．次に，4つの位置座標 x[1]=[0.0, 0.0] x[2]=[1.0, 1.0] x[3]=[1.0, 0.0] x[4]=[0.0, 1.0] を読み込んで，座標順に[1,2,3,4,1]と巡る距離を求めよ．  

1. **最大数**  
    ランダムな整数が格納されたリストを受け取り，そのリスト中の最大数を返す関数MyMaxを作れ．1から100までのランダムな整数のリストは次のようにして作れる．  

In [107]:
# 1. 三角形の面積
def area(base, height):
    '''
    Argument:
    base -- 三角形の底辺
    height -- 三角形の高さ
    
    Returns:
    三角形の面積
    '''
    return base*height/2.0

In [108]:
# 1. test
print('area: ' + str(area(10, 12)))

area: 60.0


In [109]:
# 2. MyIsprime

In [110]:
# 3. ルートの距離2つの位置座標

In [111]:
# 4. 最大数